name: Close PR and create release

on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  test:
    if: startsWith(github.head_ref, 'release/') &&  github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Clean install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  create-release:
    if: startsWith(github.head_ref, 'release/') &&  github.event.pull_request.merged == true
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Clean install dependencies
        run: npm ci
      - name: Split branch name
        id: split
        env:
          BRANCH: ${{ github.head_ref }}
        run: echo "VERSION=${BRANCH##*/}" >> "$GITHUB_OUTPUT"
      - name: Tag latest release
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.split.outputs.VERSION }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: ${{ github.head_ref }}
